stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - Dataset/raw
  
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
        - src/data_preprocessing.py
    outs:
      - Dataset/processed
  
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
        - Dataset/processed
        - src/feature_engineering.py
    outs:
      - Dataset/features
  
  model_building:
    cmd: python src/model_building.py
    deps:
        - Dataset/features
        - src/model_building.py
    outs:
      - model.pkl

  model_evalution:
    cmd: python src/model_evalution.py
    deps:
        - model.pkl
        - src/model_evalution.py
    metrics:
      - metrics.json
  


